import {
  ChangeDetectionStrategy,
  Component,
  DestroyRef,
  ElementRef,
  afterNextRender,
  inject,
  signal,
} from '@angular/core';
import { RouterLink } from '@angular/router';
import { TranslocoPipe } from '@jsverse/transloco';
import { AnalyticsService, CtaLabel } from '../../../core/analytics.service';
import { FreeCallCta } from '../../../shared/ui/free-call-cta/free-call-cta';

interface HeroSlide {
  /** Base name of the WebP variants in public/hero-carousel/. */
  readonly image: string;
  /** `brand` washes the shot in RSA blue; `warm` keeps the photo's own colour; `light` is a weaker blue for detail-preserving photos. */
  readonly overlay: 'brand' | 'warm' | 'medium' | 'light';
  /** object-position, so the subject survives the crop on portrait screens. */
  readonly focus: string;
  readonly captionKey: string;
  readonly altKey: string;
}

/** Widths generated by scripts/optimize-hero-images.py. */
const IMAGE_WIDTHS = [640, 960, 1440, 1920, 2560];

const SLIDE_DURATION_MS = 6500;

const SLIDES: readonly HeroSlide[] = [
  {
    image: 'bridge',
    overlay: 'medium',
    focus: '58% 50%',
    captionKey: 'dashboard.hero.slide1Caption',
    altKey: 'dashboard.hero.slide1Alt',
  },
  {
    image: 'tunel',
    overlay: 'warm',
    focus: '50% 50%',
    captionKey: 'dashboard.hero.slide2Caption',
    altKey: 'dashboard.hero.slide2Alt',
  },
  {
    image: 'skyscrapers',
    overlay: 'light',
    focus: '50% 55%',
    captionKey: 'dashboard.hero.slide3Caption',
    altKey: 'dashboard.hero.slide3Alt',
  },
];

/**
 * Full-bleed opening fold: three photographs crossfading behind one headline,
 * one sub-headline and a single call to action.
 *
 * The rotation is driven by a requestAnimationFrame loop rather than a timer
 * so the progress pill and the slide change can never drift apart. The loop
 * writes its progress straight to a CSS custom property, which keeps the
 * per-frame work out of change detection — only the slide index is a signal.
 */
@Component({
  selector: 'app-hero-carousel',
  imports: [RouterLink, TranslocoPipe, FreeCallCta],
  templateUrl: './hero-carousel.html',
  styleUrl: './hero-carousel.css',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class HeroCarousel {
  protected readonly slides = SLIDES;
  protected readonly activeIndex = signal(0);
  /** Set by the pause button; the reader's explicit choice, so it sticks. */
  protected readonly paused = signal(false);

  /** Hover or keyboard focus inside the hero: hold, but resume on leave. */
  private readonly interacting = signal(false);

  private readonly hostRef = inject(ElementRef<HTMLElement>);
  private readonly analytics = inject(AnalyticsService);
  private readonly destroyRef = inject(DestroyRef);

  private elapsed = 0;
  private lastFrame = 0;
  private frame: number | undefined;
  /** When true nothing rotates on its own; the pills still switch slides. */
  private reducedMotion = false;

  constructor() {
    afterNextRender(() => this.setupAutoplay());
  }

  protected srcset(slide: HeroSlide): string {
    return IMAGE_WIDTHS.map((w) => `hero-carousel/${slide.image}-${w}.webp ${w}w`).join(', ');
  }

  protected src(slide: HeroSlide): string {
    return `hero-carousel/${slide.image}-1920.webp`;
  }

  protected goTo(index: number): void {
    this.activeIndex.set(index);
    this.resetProgress();
  }

  protected togglePaused(): void {
    this.paused.update((paused) => !paused);
  }

  protected setInteracting(interacting: boolean): void {
    this.interacting.set(interacting);
  }

  protected trackCta(label: CtaLabel): void {
    this.analytics.trackCtaClick(label);
  }

  protected scrollToElement(elementId: string): void {
    setTimeout(() => {
      const el = document.getElementById(elementId);
      if (el) el.scrollIntoView({ behavior: 'smooth', block: 'start' });
    }, 0);
  }

  protected scrollToProtocol(): void {
    const el = document.getElementById('protocol');
    if (!el) return;
    const target = el.offsetTop - 80; // 5rem padding = 80px
    const start = document.documentElement.scrollTop;
    const duration = 800;
    const startTime = Date.now();
    const animate = () => {
      const elapsed = Date.now() - startTime;
      const progress = Math.min(elapsed / duration, 1);
      document.documentElement.scrollTop = start + (target - start) * progress;
      if (progress < 1) requestAnimationFrame(animate);
    };
    animate();
  }

  private setupAutoplay(): void {
    if (window.matchMedia('(prefers-reduced-motion: reduce)').matches) {
      // Nothing rotates: the chosen slide simply stays, and its pill reads full.
      this.reducedMotion = true;
      this.setProgress(1);
      return;
    }

    const onVisibility = () => (document.hidden ? this.stop() : this.start());
    document.addEventListener('visibilitychange', onVisibility);

    // A hero scrolled past has nothing to show, so it should not burn frames.
    const observer = new IntersectionObserver(
      (entries) => (entries.some((entry) => entry.isIntersecting) ? this.start() : this.stop()),
      { threshold: 0.15 },
    );
    observer.observe(this.hostRef.nativeElement);

    this.destroyRef.onDestroy(() => {
      document.removeEventListener('visibilitychange', onVisibility);
      observer.disconnect();
      this.stop();
    });
  }

  private start(): void {
    if (this.frame !== undefined) return;
    this.lastFrame = 0;
    this.frame = requestAnimationFrame((ts) => this.step(ts));
  }

  private stop(): void {
    if (this.frame === undefined) return;
    cancelAnimationFrame(this.frame);
    this.frame = undefined;
  }

  private step(timestamp: number): void {
    this.frame = requestAnimationFrame((ts) => this.step(ts));

    const delta = this.lastFrame ? timestamp - this.lastFrame : 0;
    this.lastFrame = timestamp;

    if (this.paused() || this.interacting()) return;

    this.elapsed += delta;
    if (this.elapsed >= SLIDE_DURATION_MS) {
      this.elapsed = 0;
      this.activeIndex.update((index) => (index + 1) % SLIDES.length);
    }
    this.setProgress(this.elapsed / SLIDE_DURATION_MS);
  }

  private resetProgress(): void {
    this.elapsed = 0;
    // With no rotation running the pill would never fill, so it reads as done.
    this.setProgress(this.reducedMotion ? 1 : 0);
  }

  private setProgress(value: number): void {
    this.hostRef.nativeElement.style.setProperty('--hero-progress', value.toFixed(3));
  }
}
